export enum Tag {
    SPORTS = "SPORTS",
    ROBOTICS = "ROBOTICS",
    MUSIC = "MUSIC",
    ART = "ART",
    TECHNOLOGY = "TECHNOLOGY",
    SCIENCE = "SCIENCE",
    LITERATURE = "LITERATURE",
    GAMING = "GAMING",
    COMMUNITY_SERVICE = "COMMUNITY_SERVICE",
    PHOTOGRAPHY = "PHOTOGRAPHY",
    FITNESS = "FITNESS",
    FINANCE = "FINANCE",
    ASTRONOMY = "ASTRONOMY",
    VOLUNTEERING = "VOLUNTEERING",
    LEADERSHIP = "LEADERSHIP"
}
